from django.contrib import admin
from .models import mgBCOsh,mgFronOsh,mgFullOsh,mgUIOsh,mgBCBi,mgFronBi,mgFullBi,mgUIBi,mgBCUz,mgFronUz,mgFullUz,mgUIUz,evBCOsh,evFronOsh,evFullOsh,evUIOsh,evBCBi,evFronBi,evFullBi,evUIBi,evBCUz,evFronUz,evFullUz,evUIUz

admin.site.register(mgBCOsh)
admin.site.register(mgFronOsh)
admin.site.register(mgFullOsh)
admin.site.register(mgUIOsh)
admin.site.register(mgBCBi)
admin.site.register(mgFronBi)
admin.site.register(mgFullBi)
admin.site.register(mgUIBi)
admin.site.register(mgBCUz)
admin.site.register(mgFronUz)
admin.site.register(mgFullUz)
admin.site.register(mgUIUz)
# -------------------
admin.site.register(evBCOsh)
admin.site.register(evFronOsh)
admin.site.register(evFullOsh)
admin.site.register(evUIOsh)
admin.site.register(evBCBi)
admin.site.register(evFronBi)
admin.site.register(evFullBi)
admin.site.register(evUIBi)
admin.site.register(evBCUz)
admin.site.register(evFronUz)
admin.site.register(evFullUz)
admin.site.register(evUIUz)