# Generated by Django 2.2.12 on 2021-08-14 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PersonAl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('surname', models.CharField(max_length=255, verbose_name='фамилия')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('mobile', models.CharField(blank=True, max_length=255, null=True, verbose_name='Мобильный номер')),
                ('summ', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PersonBi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('surname', models.CharField(max_length=255, verbose_name='фамилия')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('mobile', models.CharField(blank=True, max_length=255, null=True, verbose_name='Мобильный номер')),
                ('summ', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PersonOsh',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('surname', models.CharField(max_length=255, verbose_name='фамилия')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('mobile', models.CharField(blank=True, max_length=255, null=True, verbose_name='Мобильный номер')),
                ('summ', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TeacherAl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('surname', models.CharField(max_length=255, verbose_name='Фамилия')),
                ('mobile', models.CharField(blank=True, max_length=255, null=True, verbose_name='номер')),
                ('summ', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TeacherBi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('surname', models.CharField(max_length=255, verbose_name='Фамилия')),
                ('mobile', models.CharField(blank=True, max_length=255, null=True, verbose_name='номер')),
                ('summ', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TeacherOsh',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('surname', models.CharField(max_length=255, verbose_name='Фамилия')),
                ('mobile', models.CharField(blank=True, max_length=255, null=True, verbose_name='номер')),
                ('summ', models.CharField(max_length=255)),
            ],
        ),
    ]
